// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Gary Frattarola <garyf@parkviewlab.ai>
import { app, BrowserWindow, ipcMain, dialog, Menu, protocol, net, shell } from 'electron'
import { join, dirname, resolve, extname } from 'path'
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { pathToFileURL, fileURLToPath } from 'node:url'
import pkg from '../../package.json'

const isDev = !app.isPackaged
const GITHUB_URL = 'https://github.com/ParkviewLab/conception-space'

// Must be called before app is ready.
// Registers cs-file:// as a secure scheme so Chromium lets iframes load it.
protocol.registerSchemesAsPrivileged([{
  scheme:     'cs-file',
  privileges: { secure: true, supportFetchAPI: true, stream: true },
}])

let _currentFilePath = null   // last successfully opened file path

function createWindow() {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    backgroundColor: '#090916',
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      sandbox: false,
    },
  })

  const devUrl = process.env['ELECTRON_RENDERER_URL']
  if (isDev && devUrl) {
    win.loadURL(devUrl)
  } else {
    win.loadFile(join(__dirname, '../renderer/index.html'))
  }

  return win
}

let _aboutWin = null
function openAboutWindow() {
  if (_aboutWin && !_aboutWin.isDestroyed()) { _aboutWin.focus(); return }
  const html = `<!doctype html>
<meta charset="utf-8">
<style>
  html,body{margin:0;height:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
    background:#0b0b16;color:#e9e9f2;-webkit-user-select:none;cursor:default}
  .wrap{height:100%;box-sizing:border-box;padding:30px 34px;display:flex;flex-direction:column;
    align-items:center;justify-content:center;text-align:center}
  h1{margin:0;font-size:21px;font-weight:600;letter-spacing:.2px}
  .ver{margin:3px 0 18px;font-size:12px;color:#9494ac}
  p{margin:0 0 6px;font-size:13px;line-height:1.55;color:#d2d2e2;max-width:30em}
  .copy{margin:20px 0 12px;font-size:11px;color:#85859c;line-height:1.5}
  a{color:#4fc3f7;text-decoration:none;font-size:12px}
  a:hover{text-decoration:underline}
  .links{margin-top:14px;display:flex;gap:18px}
</style>
<div class="wrap">
  <h1>conception-space</h1>
  <div class="ver">Version ${pkg.version}</div>
  <p>Organize your knowledge in space.</p>
  <p>Build navigable places. Shape visible relationships. Discover emergent patterns.</p>
  <div class="copy">© 2026 Gary Frattarola — AGPL-3.0-or-later, or commercial</div>
  <div class="links">
    <a href="https://parkviewlab.ai" target="_blank" rel="noopener">parkviewlab.ai</a>
    <a href="${GITHUB_URL}" target="_blank" rel="noopener">Source code on GitHub</a>
  </div>
</div>`
  _aboutWin = new BrowserWindow({
    width: 460, height: 340,
    resizable: false, minimizable: false, maximizable: false, fullscreenable: false,
    backgroundColor: '#0b0b16',
    title: 'About conception-space',
    webPreferences: { contextIsolation: true, sandbox: true },
  })
  _aboutWin.setMenuBarVisibility(false)
  _aboutWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html))
  // Open the parkviewlab.ai link in the user's real browser, never in-app.
  _aboutWin.webContents.setWindowOpenHandler(({ url }) => { shell.openExternal(url); return { action: 'deny' } })
  _aboutWin.webContents.on('will-navigate', (e, url) => { e.preventDefault(); shell.openExternal(url) })
  _aboutWin.on('closed', () => { _aboutWin = null })
}

// The packaged legal/ notice bundle (generated by `npm run legal`). In dev it's
// the repo root; in the packaged app it's process.resourcesPath/legal.
function legalDir() {
  return app.isPackaged ? join(process.resourcesPath, 'legal') : join(__dirname, '../../legal')
}

// Marquee components called out at the top of the licenses window. Versions/links
// for production packages are pulled from oss-licenses.json; electron is a build
// dependency (its Chromium/Node notices live in LICENSES.chromium.html).
const LICENSE_HIGHLIGHTS = [
  { pkg: 'electron',   label: 'Electron',   role: 'Desktop app runtime (Chromium + Node.js)',
    note: 'MIT · bundles Chromium + Node.js', repo: 'https://github.com/electron/electron' },
  { pkg: 'three',      label: 'Three.js',   role: 'The 3D space and rendering' },
  { pkg: 'codemirror', label: 'CodeMirror', role: 'The in-app note editor' },
  { pkg: 'katex',      label: 'KaTeX',      role: 'Math typesetting in notes' },
  { pkg: 'marked',     label: 'Marked',     role: 'Markdown rendering' },
]

let _licWin = null
function openLicensesWindow() {
  if (_licWin && !_licWin.isDestroyed()) { _licWin.focus(); return }
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
  const dir = legalDir()
  const listPath = join(dir, 'oss-licenses.json')
  const noticesHref = esc(pathToFileURL(join(dir, 'THIRD-PARTY-NOTICES.txt')).href)
  const chromiumHref = esc(pathToFileURL(join(dir, 'LICENSES.chromium.html')).href)

  let body
  if (existsSync(listPath)) {
    const list = JSON.parse(readFileSync(listPath, 'utf-8'))
    const byName = Object.fromEntries(list.map((p) => [p.name, p]))
    const cards = LICENSE_HIGHLIGHTS.map((h) => {
      const p = byName[h.pkg]
      const meta = h.note || (p ? `${esc(p.license)}${p.version ? ' · v' + esc(p.version) : ''}` : '')
      const repo = (p && p.repository) || h.repo || null
      const link = repo ? ` · <a href="${esc(repo)}" target="_blank" rel="noopener">repo</a>` : ''
      return `<div class="card"><div class="hn">${esc(h.label)}</div><div class="hr">${esc(h.role)}</div><div class="hm">${meta}${link}</div></div>`
    }).join('')
    const rows = list.map((p) => {
      const name = p.repository
        ? `<a href="${esc(p.repository)}" target="_blank" rel="noopener">${esc(p.name)}</a>`
        : esc(p.name)
      return `<tr><td>${name}</td><td class="m">${esc(p.version)}</td><td class="m">${esc(p.license)}</td></tr>`
    }).join('')
    body =
      `<div class="st">Key components</div><div class="cards">${cards}</div>` +
      `<div class="st">All bundled packages (${list.length})</div>` +
      `<table><thead><tr><th>Package</th><th>Version</th><th>License</th></tr></thead><tbody>${rows}</tbody></table>` +
      `<p class="foot">Chromium &amp; Node.js notices: <a href="${chromiumHref}" target="_blank" rel="noopener">LICENSES.chromium.html</a> · ` +
      `full per-package texts: <a href="${noticesHref}" target="_blank" rel="noopener">THIRD-PARTY-NOTICES.txt</a></p>`
  } else {
    body =
      `<div class="missing">License notices are generated at package time.<br>` +
      `Run <code>npm run legal</code> in the project root, then reopen this window.</div>`
  }

  const html = `<!doctype html><meta charset="utf-8"><title>Open Source Licenses</title><style>
  :root{--bg:#090916;--panel:#0d0d1f;--line:rgba(255,255,255,.12);--accent:#4fc3f7}
  *{box-sizing:border-box}
  html,body{margin:0;height:100%}
  body{background:var(--bg);color:rgba(255,255,255,.8);font-size:13px;display:flex;flex-direction:column;
    font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}
  header{padding:16px 22px 13px;border-bottom:1px solid var(--line);flex-shrink:0}
  h1{margin:0;font-size:13px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.6)}
  .sub{margin-top:5px;font-size:12px;color:rgba(255,255,255,.4)}
  main{flex:1;overflow-y:auto;padding:2px 22px 26px;user-select:text;-webkit-user-select:text}
  .st{font-size:10px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.38);margin:20px 0 10px}
  .cards{display:flex;flex-direction:column;gap:8px}
  .card{background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:9px 13px}
  .hn{font-size:13px;font-weight:600;color:rgba(255,255,255,.9)}
  .hr{font-size:12px;color:rgba(255,255,255,.5);margin:1px 0 3px}
  .hm{font-size:11px;color:rgba(255,255,255,.42)}
  table{width:100%;border-collapse:collapse}
  th,td{border:1px solid var(--line);padding:5px 11px;text-align:left;font-size:12px}
  th{background:rgba(255,255,255,.06);color:rgba(255,255,255,.5);font-weight:600;letter-spacing:.04em}
  td{color:rgba(255,255,255,.72)} td.m{color:rgba(255,255,255,.45);white-space:nowrap}
  a{color:var(--accent);text-decoration:none} a:hover{text-decoration:underline}
  .foot{margin:18px 0 0;font-size:11px;color:rgba(255,255,255,.4);line-height:1.7}
  .missing{padding:48px 0;text-align:center;color:rgba(255,255,255,.4);line-height:1.9}
  code{background:rgba(255,255,255,.08);padding:1px 6px;border-radius:3px}
</style>
<header><h1>Open Source Licenses</h1><div class="sub">conception-space includes the open-source software below.</div></header>
<main>${body}</main>`

  _licWin = new BrowserWindow({
    width: 720, height: 640, minWidth: 460, minHeight: 360,
    backgroundColor: '#090916',
    title: 'Open Source Licenses',
    webPreferences: { contextIsolation: true, sandbox: true },
  })
  _licWin.setMenuBarVisibility(false)
  _licWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html))
  const openLink = (url) => { url.startsWith('file:') ? shell.openPath(fileURLToPath(url)) : shell.openExternal(url) }
  _licWin.webContents.setWindowOpenHandler(({ url }) => { openLink(url); return { action: 'deny' } })
  _licWin.webContents.on('will-navigate', (e, url) => { e.preventDefault(); openLink(url) })
  _licWin.on('closed', () => { _licWin = null })
}

function buildMenu(win) {
  const fileMenu = {
    label: 'File',
    submenu: [
      { label: 'Open…',        accelerator: 'CmdOrCtrl+O', click: () => openFile(win) },
      { label: 'Reload File',  accelerator: 'CmdOrCtrl+R', click: () => reloadFile(win) },
      { type: 'separator' },
      process.platform === 'darwin' ? { role: 'close' } : { role: 'quit' },
    ],
  }
  // Custom view menu: omit Reload/ForceReload (CmdOrCtrl+R is our file reload)
  const viewMenu = {
    label: 'View',
    submenu: [
      { label: 'Save Bookmark…',  accelerator: 'CmdOrCtrl+B',
        click: () => win.webContents.send('menu:save-bookmark') },
      { label: 'Go To Bookmark…', accelerator: 'CmdOrCtrl+J',
        click: () => win.webContents.send('menu:open-bookmarks') },
      { type: 'separator' },
      { role: 'toggleDevTools' },
      { type: 'separator' },
      { role: 'resetZoom' },
      { role: 'zoomIn' },
      { role: 'zoomOut' },
      { type: 'separator' },
      { role: 'togglefullscreen' },
    ],
  }
  const template = [
    ...(process.platform === 'darwin' ? [{
      label: app.name,
      submenu: [
        { label: `About ${app.name}`, click: () => openAboutWindow() },
        { label: 'Open Source Licenses…', click: () => openLicensesWindow() },
        { type: 'separator' },
        { role: 'services' },
        { type: 'separator' },
        { role: 'hide' },
        { role: 'hideOthers' },
        { role: 'unhide' },
        { type: 'separator' },
        { role: 'quit' },
      ],
    }] : []),
    fileMenu,
    { role: 'editMenu' },   // gives macOS cut/copy/paste/select-all routing
    viewMenu,
    { role: 'windowMenu' },
    {
      role: 'help',
      submenu: [
        // macOS already has About + Licenses in the app menu; add them here for Win/Linux.
        ...(process.platform !== 'darwin'
          ? [{ label: `About ${app.name}`, click: () => openAboutWindow() }, { type: 'separator' }]
          : []),
        { label: 'Open Source Licenses…', click: () => openLicensesWindow() },
        { label: 'Source Code on GitHub', click: () => shell.openExternal(GITHUB_URL) },
      ],
    },
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

async function openFile(win) {
  const { filePaths, canceled } = await dialog.showOpenDialog(win, {
    filters: [{ name: 'conception-space', extensions: ['cns', 'cs'] }],
    properties: ['openFile'],
  })
  if (canceled || !filePaths[0]) return
  _currentFilePath = filePaths[0]
  sendFile(win, _currentFilePath)
}

function reloadFile(win) {
  if (!_currentFilePath) return
  sendFile(win, _currentFilePath)
}

function sendFile(win, filePath) {
  try {
    const source = readFileSync(filePath, 'utf-8')
    win.setTitle(`${filePath.split('/').pop()} — conception-space`)
    win.webContents.send('file-loaded', { path: filePath, source })
  } catch (err) {
    console.error('[reload-file]', err.message)
  }
}

app.whenReady().then(() => {
  // cs-file:///<abs-path> → file:///<abs-path>
  // Streams straight from disk — no IPC, no base64, no memory copies.
  protocol.handle('cs-file', (req) => net.fetch(req.url.replace(/^cs-file:/, 'file:')))

  const win = createWindow()

  // Safety net: prevent the window from ever navigating away from the app.
  // Any external URL that slips through (e.g. a clicked link in an iframe) is
  // opened in the system browser instead.
  win.webContents.on('will-navigate', (e, url) => {
    const appUrl = isDev
      ? process.env['ELECTRON_RENDERER_URL']
      : `file://${join(__dirname, '../renderer/index.html')}`
    if (appUrl && !url.startsWith(appUrl)) {
      e.preventDefault()
      shell.openExternal(url)
    }
  })

  buildMenu(win)
  ipcMain.handle('open-file',      () => openFile(win))
  ipcMain.on('reload-file',        () => reloadFile(win))
  ipcMain.on('load-file',          (_e, filePath) => { _currentFilePath = filePath; sendFile(win, filePath) })
  ipcMain.handle('read-node-file', (_e, relPath) => {
    if (!_currentFilePath) return { error: 'no file loaded' }
    const abs = resolve(dirname(_currentFilePath), relPath)
    const ext = extname(abs).toLowerCase()
    try {
      if (ext === '.pdf') return { type: 'pdf', abs }
      return { type: 'md', content: readFileSync(abs, 'utf-8') }
    } catch (err) { return { error: err.message } }
  })
  ipcMain.handle('write-node-file', (_e, relPath, content) => {
    if (!_currentFilePath) return { error: 'no file loaded' }
    const abs = resolve(dirname(_currentFilePath), relPath)
    try { writeFileSync(abs, content, 'utf-8'); return { ok: true } }
    catch (err) { return { error: err.message } }
  })

  // Sidecar I/O. From foo.cns the sidecar is foo.<suffix>.json5 — v1 uses
  // suffix "views" for bookmarks; future kinds (annotations, colors, …) reuse
  // these same handlers with a different suffix string.
  const _sidecarPath = (suffix) =>
    _currentFilePath.replace(/\.(cns|cs)$/i, `.${suffix}.json5`)

  ipcMain.handle('read-sidecar', (_e, suffix) => {
    if (!_currentFilePath) return { error: 'no file loaded' }
    try { return { content: readFileSync(_sidecarPath(suffix), 'utf-8') } }
    catch (err) {
      if (err.code === 'ENOENT') return { content: null }   // no sidecar yet
      return { error: err.message }
    }
  })
  ipcMain.handle('write-sidecar', (_e, suffix, content) => {
    if (!_currentFilePath) return { error: 'no file loaded' }
    try { writeFileSync(_sidecarPath(suffix), content, 'utf-8'); return { ok: true } }
    catch (err) { return { error: err.message } }
  })
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
